# Site wide configuration

title: MELD Project
locale: en_US
description: Updates from the Multi-centre Epilepsy Lesion Detection (MELD) Project.
logo: MELD_logo.png
search: true
url: https://MELDProject.github.io/

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  enable_coderay: false

mathjax: true

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", ".less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]

repository: MELDProject/MELDProject.github.io

# Site owner
owner:
  name: Sophie Adler and Konrad Wagstyl
  avatar: MELD_logo.png
  email: MELD.study@gmail.com
  disqus-shortname:
twitter: #username
  facebook: #username
  github: MELDProject
  stackexchange: #http://stackoverflow.com/users/123456/username
  linkedin: #username
  instagram: #username
  flickr: #username
  tumblr: #username
  pinterest: #username
  weibo: #userid
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
